.PHONY: test replay deploy deploy-core cost-report vercel-files migration-sql

test:
	uv run --locked --all-packages ruff check .
	uv run --locked --all-packages ruff format --check .
	uv run --locked --all-packages pytest
	@$(MAKE) --no-print-directory vercel-files
	@git diff --exit-code --stat -- deploy/vercel || \
		(echo "deploy/vercel was out of date; commit the regenerated files" >&2; exit 1)

replay:
	uv run --locked --all-packages python -m tripvane_sensors.runtime.replay fixtures
	uv run --locked --all-packages python -m tripvane_sensors.archetypes.github.replay fixtures/github

deploy:
	@if [ -z "$(SENSOR)" ] || [ -z "$(HOST)" ]; then \
		echo "usage: make deploy SENSOR=support HOST=1.2.3.4" >&2; exit 2; fi
	infra/deploy.sh "$(SENSOR)" "$(HOST)"

deploy-core:
	@if [ -z "$(HOST)" ]; then \
		echo "usage: make deploy-core HOST=1.2.3.4" >&2; exit 2; fi
	infra/deploy-core.sh "$(HOST)"

# Yesterday (UTC) by default; DATE=YYYY-MM-DD reports another day. Reads DATABASE_URL.
cost-report:
	@uv run --locked --all-packages python -m tripvane_collector.cost $(if $(DATE),--date $(DATE))

# Files the Vercel projects need that derive from the workspace: requirements pinned from
# uv.lock, the lookup page and the site. `make test` fails while they are out of date.
vercel-files:
	@for svc in api collector; do \
		{ echo "# Generated by make vercel-files from uv.lock. Do not edit."; \
		  uv export --package tripvane-$$svc --no-dev --locked --no-hashes --no-emit-workspace \
		    --no-header --quiet; \
		  echo "../../../packages/core"; \
		  echo "../../../packages/$$svc"; } > deploy/vercel/$$svc/requirements.txt; \
	done
	@cp web/lookup.html deploy/vercel/api/public/index.html
	@rm -rf deploy/vercel/site && mkdir -p deploy/vercel/site && \
		cp -r web/index.html web/fonts deploy/vercel/site/

# The whole schema as SQL, generated without a database connection (Alembic offline mode),
# for applying through Supabase where the deploy machine cannot reach Postgres directly.
migration-sql:
	@cd packages/collector && DATABASE_URL=postgresql+psycopg://offline/tripvane \
		uv run --locked --all-packages --quiet alembic upgrade head --sql
